// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fcprd
Eigen::MatrixXf fcprd(const Eigen::MatrixXf X);
RcppExport SEXP _CoupledHalfT_fcprd(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXf >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(fcprd(X));
    return rcpp_result_gen;
END_RCPP
}
// cpp_prod
Eigen::MatrixXf cpp_prod(const Eigen::MatrixXf X, const Eigen::MatrixXf Y);
RcppExport SEXP _CoupledHalfT_cpp_prod(SEXP XSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXf >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXf >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_prod(X, Y));
    return rcpp_result_gen;
END_RCPP
}
// cpp_cholesky
Eigen::MatrixXf cpp_cholesky(const Eigen::MatrixXf M);
RcppExport SEXP _CoupledHalfT_cpp_cholesky(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXf >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_cholesky(M));
    return rcpp_result_gen;
END_RCPP
}
// rcppeigen_hello_world
Eigen::MatrixXd rcppeigen_hello_world();
RcppExport SEXP _CoupledHalfT_rcppeigen_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcppeigen_hello_world());
    return rcpp_result_gen;
END_RCPP
}
// rcppeigen_outerproduct
Eigen::MatrixXd rcppeigen_outerproduct(const Eigen::VectorXd& x);
RcppExport SEXP _CoupledHalfT_rcppeigen_outerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcppeigen_outerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// rcppeigen_innerproduct
double rcppeigen_innerproduct(const Eigen::VectorXd& x);
RcppExport SEXP _CoupledHalfT_rcppeigen_innerproduct(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcppeigen_innerproduct(x));
    return rcpp_result_gen;
END_RCPP
}
// rcppeigen_bothproducts
Rcpp::List rcppeigen_bothproducts(const Eigen::VectorXd& x);
RcppExport SEXP _CoupledHalfT_rcppeigen_bothproducts(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcppeigen_bothproducts(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CoupledHalfT_fcprd", (DL_FUNC) &_CoupledHalfT_fcprd, 1},
    {"_CoupledHalfT_cpp_prod", (DL_FUNC) &_CoupledHalfT_cpp_prod, 2},
    {"_CoupledHalfT_cpp_cholesky", (DL_FUNC) &_CoupledHalfT_cpp_cholesky, 1},
    {"_CoupledHalfT_rcppeigen_hello_world", (DL_FUNC) &_CoupledHalfT_rcppeigen_hello_world, 0},
    {"_CoupledHalfT_rcppeigen_outerproduct", (DL_FUNC) &_CoupledHalfT_rcppeigen_outerproduct, 1},
    {"_CoupledHalfT_rcppeigen_innerproduct", (DL_FUNC) &_CoupledHalfT_rcppeigen_innerproduct, 1},
    {"_CoupledHalfT_rcppeigen_bothproducts", (DL_FUNC) &_CoupledHalfT_rcppeigen_bothproducts, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_CoupledHalfT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
