# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fcprd <- function(X) {
    .Call(`_CoupledHalfT_fcprd`, X)
}

cpp_prod <- function(X, Y) {
    .Call(`_CoupledHalfT_cpp_prod`, X, Y)
}

rcppeigen_hello_world <- function() {
    .Call(`_CoupledHalfT_rcppeigen_hello_world`)
}

rcppeigen_outerproduct <- function(x) {
    .Call(`_CoupledHalfT_rcppeigen_outerproduct`, x)
}

rcppeigen_innerproduct <- function(x) {
    .Call(`_CoupledHalfT_rcppeigen_innerproduct`, x)
}

rcppeigen_bothproducts <- function(x) {
    .Call(`_CoupledHalfT_rcppeigen_bothproducts`, x)
}

